//
// Created by intellij-pest on 2020-03-05
// command
// Author: Nicholas
//

WHITESPACE = _{" " | "\t" | "\r" | "\n"}
num = @{ASCII_DIGIT+}
cmd = @{ALPHABETIC+}

raw_str = @{(!(SEPARATOR | "\"") ~ ANY)+}
escaped_str = @{
    "\"" ~ ("\\\"" | (!"\"" ~ ANY))* ~ "\""
}

arg = {num | raw_str | escaped_str}
cmd_prefix = {PUNCTUATION | MATH_SYMBOL} // Any single punctuation character or math symbol
prefixed_command = ${cmd_prefix ~ cmd}

command = {SOI ~ prefixed_command ~ arg* ~ EOI}
